include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint

custom_lint:
  rules:
    - missing_provider_scope: false

linter:
  rules:
    public_member_api_docs: false
