name: minions
description: Minions
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  logger: ^2.3.0
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.5.5
  supabase_flutter: ^2.5.6

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
