name: minions
description: Minions
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  posthog_flutter: ^4.5.0
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.6.4
  supabase_flutter: ^2.5.8
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"
  color_dark: "#0a0a0a"
  android_12:
